#!/bin/bash

#'install apache2.4 firstly'

yum -y install gcc* wget
cd && wget http://mirror.bit.edu.cn/apache//httpd/httpd-2.4.17.tar.gz
tar -xzf httpd-2.4.17.tar.gz && rm -f httpd-2.4.17.tar.gz
wget http://apache.fayea.com//apr/apr-1.5.2.tar.gz
tar -xzf apr-1.5.2.tar.gz && rm -f apr-1.5.2.tar.gz
wget http://apache.fayea.com//apr/apr-util-1.5.4.tar.gz
tar -xzf apr-util-1.5.4.tar.gz && rm -f apr-util-1.5.4.tar.gz
cp -r apr-1.5.2/ httpd-2.4.17/srclib/apr
cp -r apr-util-1.5.4/ httpd-2.4.17/srclib/apr-util
cd httpd-2.4.17
./configure --prefix=/usr/local/apache2 --sysconfdir=/usr/local/apache2/etc --with-included-apr --enable-so --enable-deflate=shared --enable-expires=shared --enable-rewrite=shared
make && make install
service httpd stop ; chkconfig httpd off
setenforce 0
sed -i '/SELINUX=enforcing/s/enforcing/permissive/' /etc/sysconfig/selinux
iptables -F ; iptables -X && service iptables save
echo '/usr/local/apache2/bin/apachectl start' >> /etc/rc.d/rc.local

#'some usages of apache2.4 are shown below:'

############################################

#'usage1: user authentication'

#'step1: enable AllowOverride (which means enable .htaccess file)'
sed -i '/AllowOverride/s/None/all/' /usr/local/apache2/etc/httpd.conf

#'step2: set access config file'
[ ! -f /usr/local/apache2/htdocs/.htaccess ]  && echo '
authname "input your username and account"
authtype basic
authuserfile /usr/local/apache2/htdocs/user_password
require valid-user
' > /usr/local/apache2/htdocs/.htaccess || echo '
.htaccess file exists!'

#'step3: generate username & password'
htpasswd -b /usr/local/apache2/htdocs/user_password root passw0rd

#'step4: remember to bounce apache!'
/usr/local/apache2/bin/apachectl stop && /usr/local/apache2/bin/apachectl start

############################################

#'usage2: address authentication (only 192.168.57.0/24 allowed), this the rule of apache2.4, not 2.2'

sed -i '/Require all granted/s@$@\n<requireall>\nrequire all granted\nrequire ip 192.168.57.0/24\n</requireall>\n@' /usr/local/apache2/etc/httpd.conf
sed -i '/Require all granted/d' /usr/local/apache2/etc/httpd.conf
/usr/local/apache2/bin/apachectl stop && /usr/local/apache2/bin/apachectl start

############################################

#'usage3: virtual hosts (diffed by addresses) on apache2.4'

sed -i '/httpd-vhosts.conf/s/#//' /usr/local/apache2/etc/httpd.conf

mv /usr/local/apache2/extra/httpd-vhosts.conf /usr/local/apache2/extra/httpd-vhosts.conf.bak && echo '

<VirtualHost *:80>
DocumentRoot "/usr/local/apache2//docs/oo.com"
ServerName oo.com
</VirtualHost>

<VirtualHost *:80>
DocumentRoot "/usr/local/apache2//docs/xx.com"
ServerName xx.com
</VirtualHost>

' > /usr/local/apache2/extra/httpd-vhosts.conf

/usr/local/apache2/bin/apachectl stop && /usr/local/apache2/bin/apachectl start

############################################

#'usage4: directory alias'

sed -i '/ServerName oo.com/s@$@\nalias "test" "/usr/local/apache2/docs/oo.com/dev/test"@' /usr/local/apache2/etc/httpd.conf
/usr/local/apache2/bin/apachectl stop && /usr/local/apache2/bin/apachectl start

############################################

#'usage5: rewrite'

#'step1: enable rewrite module'
sed -i '/rewrite_module/s/#//p' /usr/local/apache2/etc/httpd.conf

#'step2: enable .htaccess file by "allowoverride all"'
echo '
<Directory "/usr/local/apache2/docs/xx.com">
options indexes followsymlinks
allowoverride all
require all granted
</Directory>
' >> /usr/local/apache2/extra/httpd-vhosts.conf

#'step3: set rewrite rules in .htaccess file'
[ ! -f /usr/local/apache2/docs/xx.com/.htaccess ]  && echo '
rewriteengine on
rewritecond %{HTTP_HOST} xx.com
rewrite .* www.oo.com
' > /usr/local/apache2/docs/xx.com/.htaccess || echo '
.htaccess file of xx.com already exists!'

#'step4: reload configrations'
/usr/local/apache2/bin/apachectl stop && /usr/local/apache2/bin/apachectl start

############################################
