#!/bin/bash
yum -y install bind bind-utils
sed -i '/allow-query *{ localhost; };/s/localhost/any/' /etc/named.conf 
sed -i '/listen-on port 53 { 127.0.0.1; };/s/127.0.0.1/any/' /etc/named.conf 
sed -i '/^zone/,+4d' /etc/named.conf
sed -i '/rfc1912/s/include/# include/' /etc/named.conf
echo '
#set access-lists
acl local-servers {
192.168.57.0/24;
};
#add views
view lan {
match-clients { local-servers; };
recursion yes;
zone "." IN {
	type hint;
	file "named.ca";
};
zone "57.rljhs.net" IN {
type slave;
masters { 192.168.57.11; };
file "slaves/57.rljhs.net";
allow-transfer { local-servers; };
};
zone "rljhs.net" IN {
type slave;
masters { 192.168.57.11; };
file "slaves/rljhs.net";
allow-transfer { local-servers; };
};
};
view wan {
match-clients { any; };
recursion no;
zone "rljhs.net" IN {
type slave;
masters { 192.168.57.11; };
file "slaves/rljhs.net";
allow-transfer { local-servers; };
};
};
' >> /etc/named.conf
service named start
