#!/bin/bash

#'step1: install nginx'
cd && wget http://nginx.org/download/nginx-1.8.0.tar.gz
useradd -M -s /sbin/nologin nginx
tar -xzf nginx-1.8.0.tar.gz && cd nginx-1.8.0
./configure --prefix=/usr/local/nginx --user=nginx --group=nginx --with-http_stub_status_module
make && make install
/usr/local/nginx/sbin/nginx

#'step2: disable iptables & selinux'
setenforce 0
sed -i '/SELINUX=enforcing/s/enforcing/permissive/' /etc/sysconfig/selinux
iptables -F ; iptables -X && service iptables save

#'step3: create init script'
echo '
#!/bin/bash
# chkconfig: 2345 99 28
# description: Nginx web server
NGINX=/usr/local/nginx/sbin/nginx
PID_FILE=/usr/local/nginx/logs/nginx.pid
case $1 in
start)
$NGINX
$PHP
echo "NGINX is starting"
;;
stop)
kill -s QUIT $(cat $PID_FILE)
echo "NGINX is stopping"
;;
restart)
$0 stop &> /dev/null
$0 start &> /dev/null
echo "NGINX is restarting"
;;
reload)
kill -s HUP $(cat $PID_FILE)
echo "NGINX reloading"
;;
*)
echo "$0 Usage: start | stop | restart | reload"
esac
' > /etc/init.d/nginx && chmod +x /etc/init.d/nginx

